### ISSUE TITLE
problema con Project.objects.all()

### ISSUE THREAD

**Issue by MrArleking** [hcosta/web-personal-curso-django-2#1]
Estimado

Quería consultarle que al ejecutar el código siguiendo las indicaciones de su tutorial me arroja el siguiente error:
![image](https://user-images.githubusercontent.com/49913803/60676909-15afef00-9e4e-11e9-8b4e-f413dc69d397.png)
y no se como solucionarlo, este error impide que se visualice la pagina Portafolio.

**Comment by MrArleking** [comment]
> Estimado
> 
> Quería consultarle que al ejecutar el código siguiendo las indicaciones de su tutorial me arroja el siguiente error:
> ![image](https://user-images.githubusercontent.com/49913803/60676909-15afef00-9e4e-11e9-8b4e-f413dc69d397.png)
> y no se como solucionarlo, este error impide que se visualice la pagina Portafolio.

Estimado

me di cuenta que el error fue haber escrito {% for project in projects} y por eso no funcionaba

**Comment by hcguz** [comment]
Ok perfecto!
